### ISSUE TITLE
Permission denied (publickey) after one successful login

### ISSUE THREAD

**Issue by xxxcrow** [ViRb3/pi-encrypted-boot-ssh#15]
Hi, happy to see this brilliant project is still alive 💗
I did everything from the readme, logged in, tried things out
Updated and upgraded, and also upgraded the kernel(if it's related)
And after reboot I can't unlock the partition from ssh because it says Permission denied (publickey)
My public key is still in /etc/dropbear/initramfs/authorized_keys
What can be the problem? Thank you

**Comment by ViRb3** [comment]
Hey. I tested the guide end-to-end 5 days ago and everything works 100%. I updated the kernel and installed a bunch of software, restarted multiple times, no problem. That same Raspberry Pi has been running in production ever since. Make sure you are using Ubuntu 22.04 Server and you followed all the steps carefully. The only other thing I can think of is something you installed messed with the initramfs or dropbear ssh key. Sadly without any more information, I cannot really help.

**Comment by xxxcrow** [comment]
The guide is working I know, but I got some issues after
But now I did several things, and it started to work again, not sure what it was 👀
Updated initramfs, added timeout for dropbear

**Comment by metametapod** [comment]
Maybe this is obvious to others, but I was seeing this error after the first boot from the flashed SD card. It was resolved after completing step (2) linked below with keyboard and monitor:

https://github.com/ViRb3/pi-encrypted-boot-ssh?tab=readme-ov-file#on-the-raspberry-pi

and then logging in via e.g.:

```
ssh root@raspberrypi.lan
```

(`lan` is the [private TLD](https://serverfault.com/a/937808) for my network, yours may be different.)
